name: Push Docker image
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    tags:
      - '*.*.*'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get-npm-version
        uses: martinbeentjes/npm-get-version-action@main
        id: package-version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        run: docker build -t fieron/wireguard:latest -t fieron/wireguard:${{ github.ref_name }} . && \
          docker push fieron/wireguard:latest && \
          docker push fieron/wireguard:${{ github.ref_name }}

